version: '3.7'
services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        environment:
            GF_AUTH_DISABLE_LOGIN_FORM: 'true'
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
        volumes:
            - ./grafana-data:/var/lib/grafana
            # - ./provisioning:/etc/grafana/provisioning
            - ./grafana.ini:/etc/grafana/grafana.ini:ro
            - ./dashboards:/etc/grafana/dashboards
